### ISSUE TITLE
live Streaming Tv and Sport Indonesia 

### ISSUE THREAD

**Issue by fypNews** [SeppPenner/awesome-german-piracy#14]
live Streaming Tv and Sport Indonesia 
https://tv.fypnews.id

**Comment by SeppPenner** [comment]
Thanks, is added in https://github.com/SeppPenner/awesome-german-piracy/commit/cb68c0da9d44362bd0b3c8ce5a5cc07fe477008a.

**Comment by SeppPenner** [comment]
@all-contributors please add @fypNews for doc
