### ISSUE TITLE
baka-bewerbung.ml zu baka-bewerbung.me

### ISSUE THREAD

**Issue by IITuxtmuxII** [SeppPenner/awesome-german-piracy#16]
die haben die tld gewechselt zu  
baka-bewerbung.me

https://baka-bewerbung.me/form/jPQXDZ

**Comment by SeppPenner** [comment]
Danke, habe es nachgetragen: https://github.com/SeppPenner/awesome-german-piracy/commit/cf17ff9f63035eedc37f667ec9fc663cc6907570.
