### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by PierrunoYT** [SeppPenner/awesome-german-piracy#3]
Can you please sort it by language?

**Comment by SeppPenner** [comment]
I don't like to do that as the language you see in the different files is the main language of the board, not the language of the releases. E.g. the site s.to most of the time offers German and US versions of series, but its main language is German. Also, it's sometimes not really clear which main language a website has just from looking at them for few seconds...

I seperated the series and movies pages already to `German`, `English` and `Other` which mainly tracks to the language of the releases, but I don't want to seperate pages by the main language of the website...
